# Generated by Django 2.1.7 on 2019-02-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('trip_level', models.CharField(choices=[('0', 'New'), ('1', 'Noob'), ('2', 'Begginer'), ('3', 'Junior'), ('4', 'Sophomore'), ('5', 'Intermediate'), ('6', 'Backpacker'), ('7', 'Advanced'), ('8', 'High Authority'), ('9', 'Master'), ('10', 'True Traveller')], default=0, max_length=2)),
                ('based_on', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
