# Generated by Django 2.1.7 on 2019-03-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190228_1235'),
        ('users', '0005_auto_20190221_1622'),
    ]

    operations = [
    ]
