# Generated by Django 2.1.7 on 2019-03-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20190307_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='counter_verified',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
