# Generated by Django 2.1.7 on 2019-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20190309_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='date_start',
            field=models.DateField(null=True),
        ),
    ]
