# Generated by Django 2.1.7 on 2019-03-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20190310_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
