# Generated by Django 2.1.7 on 2019-03-19 14:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='trip',
            name='reported_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(choices=[('0', 'Ski & Snow'), ('1', 'Trekking'), ('2', 'Cultural'), ('3', 'Beach'), ('4', 'Party'), ('5', 'Festival'), ('6', 'Surf'), ('7', 'None')], max_length=1, null=True),
        ),
    ]
