# Generated by Django 2.1.7 on 2019-02-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190221_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('1', 'new follower'), ('2', 'new comment'), ('3', 'upgrade_level'), ('4', 'trip_verification'), ('5', 'trusted_trip'), ('6', 'fake_trip')], max_length=1),
        ),
    ]
