# Generated by Django 2.1.7 on 2019-03-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20190222_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='trip_related',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
