# Generated by Django 2.1.7 on 2019-03-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20190301_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('0', 'new follower'), ('1', 'new comment'), ('2', 'upgrade_level'), ('3', 'trip_verification'), ('4', 'trusted_trip'), ('5', 'fake_trip')], max_length=1),
        ),
    ]
