# Generated by Django 2.1.7 on 2019-03-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_auto_20190313_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('0', 'new_follower'), ('1', 'new_comment'), ('2', 'upgrade_level'), ('3', 'trip_verification'), ('4', 'trusted_trip'), ('5', 'fake_trip'), ('6', 'added_to_trip')], max_length=1),
        ),
    ]
