# Generated by Django 2.1.7 on 2019-03-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20190316_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='from_user',
            field=models.IntegerField(default=None),
        ),
    ]
