# Generated by Django 2.1.7 on 2019-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20190317_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('0', 'new_follower'), ('1', 'new_comment'), ('2', 'upgrade_level'), ('3', 'trip_verification'), ('4', 'trusted_trip'), ('5', 'fake_trip_under_investigation'), ('6', 'added_to_trip'), ('7', 'like_trip')], max_length=1),
        ),
    ]
